spring:
  application:
    name: micro1
  data:
    mongodb:
      uri: mongodb://localhost:27017/mesero2023iv
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#okta:
#  oauth2:
#    issuer: https://TU_OKTA_DOMAIN/oauth2/default
#    client-id: TU_CLIENT_ID
#    client-secret: TU_CLIENT_SECRET